# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-ISBN-AmazonFR_Driver
version:      0.02
version_from: lib/WWW/Scraper/ISBN/AmazonFR_Driver.pm
installdirs:  site
requires:
    Test::More:                    0.45
    WWW::Mechanize:                0
    WWW::Scraper::ISBN:            0.25
    WWW::Scraper::ISBN::Driver:    0.18
    WWW::Scraper::ISBN::Record:    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
